module.exports.actionTypes = {
    //Indexing
    'INDEX_ALL_WORDS_START': 'INDEX_ALL_WORDS_START',
    'INDEX_ALL_WORDS_SUCCESS': 'INDEX_ALL_WORDS_SUCCESS',
    'INDEX_ALL_WORDS_FAILURE': 'INDEX_ALL_WORDS_FAILURE',

    //Status
    'GET_INDEXING_STATUS_START': 'GET_INDEXING_STATUS_START',
    'GET_INDEXING_STATUS_SUCCESS': 'GET_INDEXING_STATUS_SUCCESS',
    'GET_INDEXING_STATUS_FAILURE': 'GET_INDEXING_STATUS_FAILURE',

    //Add word
    'UPDATE_ADD_WORD': 'UPDATE_ADD_WORD',
    'ADD_WORD_TO_SET_START': 'ADD_WORD_TO_SET_START',
    'ADD_WORD_TO_SET_SUCCESS': 'ADD_WORD_TO_SET_SUCCESS',
    'ADD_WORD_TO_SET_FAILURE': 'ADD_WORD_TO_SET_FAILURE',

    //Test word
    'UPDATE_TEST_WORD': 'UPDATE_TEST_WORD',
};