module.exports.actionTypes = {
    'INDEX_ALL_WORDS_START': 'INDEX_ALL_WORDS_START',
    'INDEX_ALL_WORDS_SUCCESS': 'INDEX_ALL_WORDS_SUCCESS',
    'INDEX_ALL_WORDS_FAILURE': 'INDEX_ALL_WORDS_FAILURE',
};